### ISSUE TITLE
Example to setup existing kafka

### ISSUE THREAD

**Issue by shiosai** [TouK/nussknacker-helm#53]
Hi everyone, I was very curious about trying nussknacker with an existing kafka test cluster + security + confluent schema registry.

Would it be possible to add an example just for that use-case? The documentation is not very detailed. I understand everything has to be done somehow via envs and that is how we do it with other tools but it would be helpful to have a clear example.

Thanks

**Comment by mproch** [comment]
Hi shiosai,
sorry for letting you wait so long. We'll come up with example with details in the repo, meanwhile I'll pass the config we were using for testing our cloud offering:
```yaml
nussknacker:
  kafka:
    bootstrapServers: "xxxxxx.europe-central2.gcp.confluent.cloud:9092"
  modelConfig:
    kafka:
      kafkaProperties:
        "schema.registry.url": "https://xxxxxx.europe-west3.gcp.confluent.cloud"
        "security.protocol": "SASL_SSL"
        "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username = \"xxxxxx\" password=\"xxxxxx\";"
        "sasl.mechanism": "PLAIN"
        "basic.auth.credentials.source": "USER_INFO"
        "basic.auth.user.info": "xxxxxx"
```
if you're using authentication via client certificates, it's a bit more difficult, as you have to pass it with secrets
